services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-modified
    ports:
      - "8080:8080" # Map Jenkins UI to host port 8080
      - "50000:50000" # Map Jenkins agent port to host
    volumes:
      - ./jenkins_data:/var/jenkins_home
    restart: unless-stopped